stages:
  - build
  - test
  - production

before_script:
  - docker login -u "CI_REGISTRY_USER" -p "CI_REGISTRY_PASSWORD" $CI_REGISTRY

docker_job:
  stage: build
  script:
    - docker build -t .

#test_unit_job:
#  stage: test
#  script:
#    - echo 'Testing 1'
#
#test_integration_job:
#  stage: test
#  script:
#    - echo 'Testing 2'

production:
  stage: production
  when: manual
  script:
    - docker-compose up -d
#  environment:
#    name: production
#    url: https://example.com
#