---
- name: Create a directory if it does not exist
  hosts: monitoring
  become: yes
  tasks:
  - file:
      path: "{{ item }}"
      state: directory
      owner: rmntrvn
      group: rmntrvn
      mode: '0755'
    with_items:
      - /home/rmntrvn/monitoring/
      - /home/rmntrvn/monitoring/prometheus/
      - /home/rmntrvn/monitoring/alertmanager/
      - /home/rmntrvn/monitoring/grafana

- name: Prepare docker-compose files
  hosts: monitoring
  tasks:
  - copy:
      src: ../files/monitoring/
      dest: /home/rmntrvn/monitoring/
      owner: rmntrvn
      group: rmntrvn
#      mode: '0755'
#      directory_mode: yes

- name: Deploy compose services
  hosts: monitoring
  become: true
  tasks:
  - docker_compose:
      project_src: '/home/rmntrvn/monitoring/'
    register: output
