---
- name: Create a directory if it does not exist
  hosts: web
  tasks:
  - file:
      path: /home/rmntrvn/wikijs/
      state: directory
      mode: '0755'

- name: Prepare docker-compose files
  hosts: web
  tasks:
  - copy:
      src: "{{ item }}" 
      dest: /home/rmntrvn/wikijs/
      owner: rmntrvn
      group: rmntrvn
      mode: '0644'
    with_items:
      - ../files/web/docker-compose.yml
      - ../files/web/default.conf

- name: Extract wiki.js archive to repo directory
  hosts: web
  tasks:
    - unarchive:
        src: https://github.com/Requarks/wiki/releases/download/2.3.81/wiki-js-windows.tar.gz
        dest: /home/rmntrvn/wikijs/
        remote_src: yes

#- name: Deploy compose services
#  hosts: web
#  become: true
#  tasks:
#  - docker_compose:
#      project_src: '/home/rmntrvn/wikijs/'
#    register: output