---
plugin: gcp_compute
projects:
  - infra-263911
zones:
  - "europe-west1-b"
filters: []
auth_kind: serviceaccount
service_account_file: "./infra-263911-b4b2bd53434c.json"
hostnames:
  # List host by name instead of the default public ip
  - name
compose:
  # Set an inventory parameter to use the Public IP address to connect to the host
  # For Private ip use "networkInterfaces[0].networkIP"
  ansible_host: networkInterfaces[0].accessConfigs[0].natIP